# Generated by Django 5.2.5 on 2026-01-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_contactsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripbooking',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
